Repository XcodesOrg/XcodesApp, pull requests merged in 2021-02, with the labels that each got.

#95 Add Homebrew Cask install instructions
  README.md
Labels: documentation

#102 When downloading, use the downloader from userdefaults
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState.swift
Labels: bugfix

#100 Improve how identical builds are represented in the UI
  Xcodes/Backend/AppState+Update.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Backend/Version+Xcode.swift
  Xcodes/Backend/Version+XcodeReleases.swift
  Xcodes/Backend/Xcode.swift
  Xcodes/Frontend/XcodeList/InfoPane.swift
  Xcodes/Frontend/XcodeList/XcodeListView.swift
  Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
  XcodesTests/AppStateUpdateTests.swift
Labels: bugfix

#103 Remove info pane from split view instead of hiding it
  Xcodes/Frontend/MainWindow.swift
Labels: bugfix

#107 Display installation steps with download stats in info pane
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Backend/Environment.swift
  Xcodes/Backend/Progress+.swift
  Xcodes/Frontend/Common/ObservingProgressIndicator.swift
  Xcodes/Frontend/InfoPane/InfoPane.swift
  Xcodes/Frontend/InfoPane/InstallationStepDetailView.swift
  Xcodes/Frontend/XcodeList/InstallationStepRowView.swift
  Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
Labels: enhancement

#111 Add install and update instructions to release notes
  .github/release-drafter.yml
  README.md
Labels: documentation
