Repository XcodesOrg/XcodesApp, pull requests merged in 2021-05, with the labels that each got.

#129 Show sign in errors inline on sign in view
  Xcodes/AppleAPI/Sources/AppleAPI/Client.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Frontend/MainWindow.swift
  Xcodes/Frontend/SignIn/SignInCredentialsView.swift
Labels: enhancement

#130 include updates to sparkle license
  Xcodes/Resources/Licenses.rtf
Labels: chore

#126 Adds MacOS notifications
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Backend/Environment.swift
  Xcodes/Backend/NotificationManager.swift
  Xcodes/Frontend/Preferences/GeneralPreferencePane.swift
  Xcodes/Frontend/Preferences/NotificationsView.swift
Labels: enhancement

#131 only present a single alert at time
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState+Update.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Backend/XcodeCommands.swift
  Xcodes/Frontend/Common/XcodesAlert.swift
  Xcodes/Frontend/MainWindow.swift
  Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
Labels: bugfix
