Repository XcodesOrg/XcodesApp, pull requests merged in 2022-09, with the labels that each got.

#280 Fix "Unarchiving" localization in Japanese
  Xcodes/Resources/ja.lproj/Localizable.strings
Labels: localization

#284 Fix Finnish language name typo in README
  README.md
Labels: chore

#277 Added Turkish missing translations in 1.7.0
  Xcodes/Resources/tr.lproj/Localizable.strings
Labels: localization

#285 updated German translation
  Xcodes/Resources/de.lproj/Localizable.strings
Labels: localization

#290 Add ability to download Xcode without logging in using XcodeReleases
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Backend/AvailableXcode.swift
  Xcodes/Backend/Environment.swift
  Xcodes/Backend/URLRequest+Apple.swift
Labels: enhancement

#296 Typo in German Localization File
  Xcodes/Resources/de.lproj/Localizable.strings
Labels: localization
