Repository XcodesOrg/XcodesApp, pull requests merged in 2022-11, with the labels that each got.

#303 fix: Preference button on toolbar not working on Mac OS 13 Ventura
  Xcodes/Frontend/XcodeList/MainToolbar.swift
Labels: bugfix

#308 Remove localization from apple.com links
  Xcodes/Resources/de.lproj/Localizable.strings
  Xcodes/Resources/en.lproj/Localizable.strings
  Xcodes/Resources/es.lproj/Localizable.strings
  Xcodes/Resources/fi.lproj/Localizable.strings
  Xcodes/Resources/fr.lproj/Localizable.strings
  Xcodes/Resources/hi.lproj/Localizable.strings
  Xcodes/Resources/it.lproj/Localizable.strings
  Xcodes/Resources/ja.lproj/Localizable.strings
  Xcodes/Resources/ko.lproj/Localizable.strings
  Xcodes/Resources/ru.lproj/Localizable.strings
  Xcodes/Resources/tr.lproj/Localizable.strings
  Xcodes/Resources/uk.lproj/Localizable.strings
  Xcodes/Resources/zh-Hans.lproj/Localizable.strings
  Xcodes/Resources/zh-Hant.lproj/Localizable.strings
Labels: localization

#309 Fix localization on UnsupportedFileFormat
  Xcodes/Backend/AppState+Install.swift
Labels: localization

#305 move download settings to own PreferencePane
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift
  Xcodes/Frontend/Preferences/DownloadPreferencePane.swift
  Xcodes/Frontend/Preferences/PreferencesView.swift
  Xcodes/Resources/de.lproj/Localizable.strings
  Xcodes/Resources/en.lproj/Localizable.strings
  Xcodes/Resources/es.lproj/Localizable.strings
  Xcodes/Resources/fi.lproj/Localizable.strings
  Xcodes/Resources/fr.lproj/Localizable.strings
  Xcodes/Resources/hi.lproj/Localizable.strings
  Xcodes/Resources/it.lproj/Localizable.strings
  Xcodes/Resources/ja.lproj/Localizable.strings
  Xcodes/Resources/ko.lproj/Localizable.strings
  Xcodes/Resources/ru.lproj/Localizable.strings
  Xcodes/Resources/tr.lproj/Localizable.strings
  Xcodes/Resources/uk.lproj/Localizable.strings
  Xcodes/Resources/zh-Hans.lproj/Localizable.strings
  Xcodes/Resources/zh-Hant.lproj/Localizable.strings
Labels: enhancement

#306 add error message when trying to uninstall Xcode if file not found
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Backend/FileError.swift
  Xcodes/Backend/FileManager+.swift
  Xcodes/Resources/de.lproj/Localizable.strings
  Xcodes/Resources/en.lproj/Localizable.strings
Labels: enhancement

#307 Add Dutch localization
  README.md
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Resources/nl.lproj/Localizable.strings
Labels: localization

#328 Switch Xcode releases back to using Apple Auth :(
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState.swift
Labels: bugfix

#260 Add brazilian portuguese localization
  README.md
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Resources/pt-BR.lproj/Localizable.strings
Labels: localization

#304 Adds an option to save beta versions with `-beta` symlink
  .gitignore
  Xcodes/Backend/AppState.swift
  Xcodes/Backend/XcodeCommands.swift
  Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
  Xcodes/Resources/de.lproj/Localizable.strings
  Xcodes/Resources/en.lproj/Localizable.strings
  Xcodes/Resources/es.lproj/Localizable.strings
  Xcodes/Resources/fi.lproj/Localizable.strings
  Xcodes/Resources/fr.lproj/Localizable.strings
  Xcodes/Resources/hi.lproj/Localizable.strings
  Xcodes/Resources/it.lproj/Localizable.strings
  Xcodes/Resources/ja.lproj/Localizable.strings
  Xcodes/Resources/ko.lproj/Localizable.strings
  Xcodes/Resources/ru.lproj/Localizable.strings
  Xcodes/Resources/tr.lproj/Localizable.strings
  Xcodes/Resources/uk.lproj/Localizable.strings
  Xcodes/Resources/zh-Hans.lproj/Localizable.strings
  Xcodes/Resources/zh-Hant.lproj/Localizable.strings
Labels: enhancement

#322 Improve Spanish localization in Preferences
  Xcodes/Resources/es.lproj/Localizable.strings
Labels: enhancement
