Repository XcodesOrg/XcodesApp, pull requests merged in 2023-02, with the labels that each got.

#349 Ventura UI fixes
  Xcodes/Frontend/XcodeList/BottomStatusBar.swift
  Xcodes/Frontend/XcodeList/MainToolbar.swift
Labels: bugfix

#299 Update Japanese localization
  Xcodes/Resources/ja.lproj/Localizable.strings
Labels: localization

#348 Updating the username
  README.md
Labels: chore

#356 Update unxip binary to 1.1.3
  Xcodes/Resources/unxip
Labels: enhancement
