Repository XcodesOrg/XcodesApp, pull requests merged in 2023-11, with the labels that each got.

#297 Add catalan translation
  README.md
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Resources/ca.lproj/Localizable.strings
Labels: localization

#393 Update DE localization
  Xcodes/Resources/de.lproj/Localizable.strings
Labels: localization

#398 Add PinCodeTextField autocomplete support
  Xcodes/Frontend/SignIn/PinCodeTextView.swift
  Xcodes/Frontend/SignIn/SignIn2FAView.swift
  Xcodes/Frontend/SignIn/SignInSMSView.swift
Labels: enhancement

#423 Add installation progress bar to dock icon
  .github/workflows/ci.yml
  Xcodes.xcodeproj/project.pbxproj
  Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Resources/Licenses.rtf
Labels: enhancement

#428 Fix SMS Enter Digit Code Crash
  Xcodes/Resources/de.lproj/Localizable.strings
  Xcodes/Resources/en.lproj/Localizable.strings
  Xcodes/Resources/es.lproj/Localizable.strings
  Xcodes/Resources/fi.lproj/Localizable.strings
  Xcodes/Resources/fr.lproj/Localizable.strings
  Xcodes/Resources/hi.lproj/Localizable.strings
  Xcodes/Resources/ja.lproj/Localizable.strings
  Xcodes/Resources/ko.lproj/Localizable.strings
  Xcodes/Resources/nl.lproj/Localizable.strings
  Xcodes/Resources/pl.lproj/Localizable.strings
  Xcodes/Resources/pt-BR.lproj/Localizable.strings
  Xcodes/Resources/ru.lproj/Localizable.strings
  Xcodes/Resources/tr.lproj/Localizable.strings
  Xcodes/Resources/uk.lproj/Localizable.strings
  Xcodes/Resources/zh-Hans.lproj/Localizable.strings
  Xcodes/Resources/zh-Hant.lproj/Localizable.strings
Labels: localization

#443 cleans up project team so it builds
  Xcodes.xcodeproj/project.pbxproj
Labels: chore

#444 fix: settings link on Sonoma not working
  .github/workflows/ci.yml
  Xcodes/Frontend/XcodeList/MainToolbar.swift
Labels: bugfix

#436 Clean up code in `InfoPane` to be more robust
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Backend/AppState.swift
  Xcodes/Backend/XcodeCommands.swift
  Xcodes/Frontend/InfoPane/CompatibilityView.swift
  Xcodes/Frontend/InfoPane/CompilersView.swift
  Xcodes/Frontend/InfoPane/IconView.swift
  Xcodes/Frontend/InfoPane/IdenticalBuildView.swift
  Xcodes/Frontend/InfoPane/InfoPane.swift
  Xcodes/Frontend/InfoPane/InfoPaneControls.swift
  Xcodes/Frontend/InfoPane/InstallationStepDetailView.swift
  Xcodes/Frontend/InfoPane/InstalledStateButtons.swift
  Xcodes/Frontend/InfoPane/NotInstalledStateButtons.swift
  Xcodes/Frontend/InfoPane/ReleaseDateView.swift
  Xcodes/Frontend/InfoPane/ReleaseNotesView.swift
  Xcodes/Frontend/InfoPane/SDKsView.swift
  Xcodes/Frontend/InfoPane/UnselectedView.swift
  Xcodes/Frontend/MainWindow.swift
  Xcodes/XcodesApp.swift
Labels: chore
