Repository XcodesOrg/XcodesApp, pull requests merged in 2023-05, with the labels that each got.

#375 Introduce Polish translations
  README.md
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Resources/pl.lproj/Localizable.strings
Labels: localization

#371 Update unxip binary to v2.1
  Xcodes/Resources/unxip
Labels: dependencies

#386 Improve Brazilian Portuguese translation
  Xcodes/Resources/pt-BR.lproj/Localizable.strings
Labels: bugfix
