Repository XcodesOrg/XcodesApp, pull requests merged in 2024-10, with the labels that each got.

#609 Fix one Greek localization. Add one zh_Hans localization.
  Xcodes/Resources/Localizable.xcstrings
Labels: localization

#593 Update translation in zh-Hant
  Xcodes/Resources/Localizable.xcstrings
Labels: localization

#598 Update Localizable.xcstrings for Russian language (3)
  Xcodes/Resources/Localizable.xcstrings
Labels: localization

#569 Disallow changes to managed preferences
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState+Runtimes.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Backend/DataSource.swift
  Xcodes/Backend/Downloader.swift
  Xcodes/Frontend/Preferences/AdvancedPreferencePane.swift
  Xcodes/Frontend/Preferences/DownloadPreferencePane.swift
  Xcodes/Frontend/Preferences/ExperiementsPreferencePane.swift
  Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift
  Xcodes/Frontend/XcodeList/MainToolbar.swift
  Xcodes/Frontend/XcodeList/XcodeListCategory.swift
Labels: enhancement

#621 Terminate Xcodes app after last window closed
  Xcodes/Backend/AppState.swift
  Xcodes/Frontend/Preferences/GeneralPreferencePane.swift
  Xcodes/Resources/Localizable.xcstrings
  Xcodes/XcodesApp.swift
Labels: enhancement

#628 allow cancelling of runtime downloads, cleanup
  Xcodes/Backend/AppState+Runtimes.swift
  Xcodes/Resources/Localizable.xcstrings
Labels: enhancement

#640 Support SRP Login
  README.md
  Xcodes.xcodeproj/project.pbxproj
  Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Xcodes/AppleAPI/Package.swift
  Xcodes/AppleAPI/Sources/AppleAPI/Client.swift
  Xcodes/AppleAPI/Sources/AppleAPI/URLRequest+Apple.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Resources/Licenses.rtf
  XcodesTests/AppStateUpdateTests.swift
Labels: bugfix
