Repository XcodesOrg/XcodesApp, pull requests merged in 2024-01, with the labels that each got.

#463 Add new Platforms List Window
  Xcodes.xcodeproj/project.pbxproj
  Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Xcodes/Backend/AppState+Install.swift
  Xcodes/Backend/AppState+Runtimes.swift
  Xcodes/Backend/AppState.swift
  Xcodes/Frontend/Common/XcodesAlert.swift
  Xcodes/Frontend/InfoPane/InfoPane.swift
  Xcodes/Frontend/InfoPane/PlatformsView.swift
  Xcodes/Frontend/MainWindow.swift
  Xcodes/Frontend/Preferences/PlatformsListView.swift
  Xcodes/Frontend/XcodeList/XcodeListView.swift
  Xcodes/Resources/Licenses.rtf
  Xcodes/Resources/Localizable.xcstrings
  Xcodes/XcodesApp.swift
  Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/CoreSimulatorImage.swift
  Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/RuntimeInstallState.swift
  Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/RuntimeInstallationStep.swift
  Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/Runtimes.swift
  Xcodes/XcodesKit/Sources/XcodesKit/Services/RuntimeService.swift
  Xcodes/XcodesKit/Sources/XcodesKit/Shell/XcodesShell.swift
Labels: enhancement

#469 update Sparkle to 2.5.2
  Xcodes.xcodeproj/project.pbxproj
  Xcodes.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Xcodes/Frontend/Preferences/UpdatesPreferencePane.swift
  Xcodes/Resources/Licenses.rtf
Labels: enhancement

#470 Handle preference alerts from the PlatformsListView
  Xcodes/XcodesApp.swift
Labels: 2.0 Beta

#477 Add latest missing french translations
  Xcodes/Resources/Localizable.xcstrings
Labels: localization

#481 Add Sponsor/Donate Button
  Xcodes/Frontend/About/AboutView.swift
  Xcodes/Frontend/XcodeList/BottomStatusBar.swift
  Xcodes/Resources/Localizable.xcstrings
Labels: enhancement

#480 Update privilege helper to xcodesOrg and Team
  HelperXPCShared/HelperXPCShared.swift
  README.md
  Scripts/uninstall_privileged_helper.sh
  Xcodes.xcodeproj/project.pbxproj
  Xcodes.xcodeproj/xcshareddata/xcschemes/com.robotsandpencils.XcodesApp.Helper.xcscheme
  Xcodes/Resources/Info.plist
  com.xcodesorg.xcodesapp.Helper/AuditTokenHack.h
  com.xcodesorg.xcodesapp.Helper/AuditTokenHack.m
  com.xcodesorg.xcodesapp.Helper/ConnectionVerifier.swift
  com.xcodesorg.xcodesapp.Helper/Info.plist
  com.xcodesorg.xcodesapp.Helper/Logger.swift
  com.xcodesorg.xcodesapp.Helper/SimpleXPCApp.LICENSE
  com.xcodesorg.xcodesapp.Helper/XPCDelegate.swift
  com.xcodesorg.xcodesapp.Helper/com.xcodesorg.xcodesapp.Helper-Bridging-Header.h
  com.xcodesorg.xcodesapp.Helper/com.xcodesorg.xcodesapp.HelperTest.entitlements
  com.xcodesorg.xcodesapp.Helper/launchd.plist
  com.xcodesorg.xcodesapp.Helper/main.swift
Labels: bugfix

#472 Remove newline from derived data path returned by defaults
  Xcodes/AcknowledgementsGenerator/Sources/AcknowledgementsGenerator/Tools/Xcode.swift
Labels: chore
