Repository XcodesOrg/XcodesApp, pull requests merged in 2024-03, with the labels that each got.

#505 Greek language localization
  Xcodes/Resources/Localizable.xcstrings
Labels: localization

#502 l10n(zh-Hant): Update translation for 2.0.2
  Xcodes/Resources/Localizable.xcstrings
Labels: localization

#523 fix runtime not appearing when multiple runtimes exist for same build
  Xcodes/Backend/AppState+Runtimes.swift
  Xcodes/Frontend/InfoPane/InfoPane.swift
  Xcodes/Frontend/InfoPane/PlatformsView.swift
  Xcodes/XcodesKit/Sources/XcodesKit/Models/Runtimes/Runtimes.swift
Labels: bugfix

#521 Improve signing experience when using non-english keyboard
  Xcodes/Frontend/SignIn/SignInCredentialsView.swift
Labels: enhancement

#504 Improve the layout of the sidebar
  Xcodes/Frontend/Common/NavigationSplitViewWrapper.swift
  Xcodes/Frontend/MainWindow.swift
  Xcodes/Frontend/XcodeList/MainToolbar.swift
  Xcodes/Frontend/XcodeList/XcodeListView.swift
  Xcodes/Frontend/XcodeList/XcodeListViewRow.swift
  Xcodes/Resources/Assets.xcassets/xcode-beta.imageset/Contents.json
  Xcodes/Resources/Assets.xcassets/xcode-beta.imageset/Image.png
  Xcodes/Resources/Assets.xcassets/xcode.imageset/Contents.json
  Xcodes/Resources/Assets.xcassets/xcode.imageset/xcode.png
  Xcodes/Resources/Localizable.xcstrings
Labels: enhancement

#519 Updated german localization
  Xcodes/Resources/Localizable.xcstrings
Labels: localization

#527 Remove outdated version checks
  Xcodes.xcodeproj/project.pbxproj
  Xcodes/Frontend/Common/NavigationSplitViewWrapper.swift
  Xcodes/Frontend/MainWindow.swift
  Xcodes/XcodesApp.swift
Labels: chore

#530 replace default icon in info page
  Xcodes/Frontend/InfoPane/IconView.swift
  Xcodes/Frontend/InfoPane/InfoPane.swift
Labels: enhancement

#531 Replace AttributedText with markdown to fix the layout issues
  Xcodes/Frontend/Preferences/DownloadPreferencePane.swift
  Xcodes/Frontend/Preferences/ExperiementsPreferencePane.swift
  Xcodes/Frontend/SignIn/SignInPhoneListView.swift
  Xcodes/Resources/Localizable.xcstrings
Labels: enhancement

#538 fix: xcode list row text hidden on macOS 14.4
  Xcodes/Frontend/XcodeList/XcodeListView.swift
Labels: bugfix

#533 adds localization validation on PR's
  .github/workflows/xcstrings.yml
  Xcodes/Resources/Localizable.xcstrings
Labels: chore
